config_version = 12

[backdrop]
blur_intensity = 0.5
enabled = true
tint_intensity = 0.29999999999999999

[bar]
order = [ "bar", "default" ]

    [bar.bar]
    background_opacity = 0.79999998211860657
    center = [ "clock", "spacer_2", "ram", "cpu" ]
    enabled = true
    end = [
        "media",
        "tray",
        "spacer_3",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "spacer_4",
        "notifications"
    ]
    font_family = "JetBrainsMono NF"
    margin_edge = 5
    margin_ends = 300
    padding = 20
    radius = 50
    start = [ "custom_button_2", "workspaces" ]
    widget_spacing = 10

    [bar.default]
    enabled = false

[desktop_widgets]
enabled = false

[hooks]
theme_mode_changed = "pkill -USR1 -f qt6ct || true"

[location]
address = "Berlin, Germany"

[lockscreen]
blur_intensity = 0.0
tint_intensity = 0.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@Virtual-1", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1066.5
    cy = 922.0
    output = "Virtual-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.80000000000000004
        background_radius = 32.0
        center_password_text = false
        input_opacity = 0.80000000000000004
        input_radius = 32.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 144.0
    box_width = 272.0
    cx = 1066.5
    cy = 240.0
    output = "Virtual-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        background_color = "on_secondary"
        background_opacity = 0.44
        background_padding = 17
        background_radius = 0
        clock_style = "digital"
        shadow = true

[plugin_settings."nightwatch75/todo"]
panel_open_near_click = false
panel_placement = "floating"
panel_position = "center"

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"
browser_position = "center"
download_dir = "/home/leo/dotfiles/resources/wallpapers"

[plugins]
enabled = [ "noctalia/wallhaven" ]

[shell]
avatar_path = "/home/leo/dotfiles/resources/profile-pictures/hollow-knight.jpg"
font_family = "JetBrainsMono NF"

    [shell.panel]
    transparency_mode = "soft"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

[templates.gtk3]
input_path = "/usr/share/noctalia/assets/templates/gtk/noctalia.css"
output_path = "~/.config/gtk-3.0/noctalia.css"
post_hook = "bash /usr/share/noctalia/assets/templates/gtk/apply.sh dark"

[templates.gtk4]
input_path = "/usr/share/noctalia/assets/templates/gtk/noctalia.css"
output_path = "~/.config/gtk-4.0/noctalia.css"
post_hook = "bash /usr/share/noctalia/assets/templates/gtk/apply.sh dark"

[templates.nvim-base16]
input_path = "~/.config/nvim/lua/matugen-template.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = "pkill -SIGUSR1 nvim"

[templates.qt5ct]
input_path = "~/.config/noctalia/templates/noctalia.colors"
output_path = "~/.config/qt5ct/colors/noctalia.conf"

[templates.qt6ct]
input_path = "~/.config/noctalia/templates/noctalia.colors"
output_path = "~/.config/qt6ct/colors/noctalia.conf"

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kitty", "mango", "qt" ]
    community_ids = [ "pywalfox-beta4", "neovim", "fastfetch", "bat", "yazi" ]

[wallpaper]
directory = "/home/leo/dotfiles/resources/wallpapers"

    [wallpaper.automation]
    order = "alphabetical"

    [wallpaper.default]
    path = "/home/leo/dotfiles/resources/wallpapers/hollow_knight.jpg"

    [wallpaper.last]
    path = "/home/leo/dotfiles/resources/wallpapers/hollow_knight.jpg"

    [wallpaper.monitors.Virtual-1]
    path = "/home/leo/dotfiles/resources/wallpapers/hollow_knight.jpg"

[widget.custom_button_2]
custom_image = "/home/leo/dotfiles/resources/nixos-icon.png"
custom_image_colorize = true
icon_color = "primary"
interactive = false
scale = 1.25
type = "custom_button"

[widget.media]
album_art_only = true
hide_when_no_media = true

[widget.spacer_2]
type = "spacer"

[widget.spacer_3]
type = "spacer"

[widget.spacer_4]
type = "spacer"

[widget.workspaces]
active_pill_size = 1.0
capsule_opacity = 0.5
capsule_radius = "auto"
empty_color = "outline"
hide_when_empty = true
label_source = "id"
pill_scale = 0.80000000000000004
style = "minimal"