[bar]
order = [ "bar", "default" ]

    [bar.bar]
    center = [ "ram", "cpu" ]
    enabled = true
    end = [ "media", "tray", "notifications", "network", "bluetooth", "volume", "brightness", "battery" ]
    font_family = "JetBrainsMono NF"
    margin_edge = 2
    padding = 10
    radius = 50
    start = [ "clock", "workspaces" ]

    [bar.default]
    enabled = false

[desktop_widgets]
enabled = false

[hooks]
theme_mode_changed = "pkill -USR1 -f qt6ct || true"

[location]
address = "Berlin, Germany"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@Virtual-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1067.0
    cy = 1018.0
    output = "Virtual-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"
browser_position = "center"
download_dir = "/home/leo/dotfiles/resources/wallpapers"

[plugins]
enabled = [ "noctalia/wallhaven" ]

[shell]
avatar_path = "/home/leo/dotfiles/resources/profile-pictures/cat-white.jpg"
font_family = "JetBrainsMono NF"

    [shell.panel]
    wallpaper_placement = "floating"
    wallpaper_position = "center"

[templates.gtk3]
input_path = "/usr/share/noctalia/assets/templates/gtk/noctalia.css"
output_path = "~/.config/gtk-3.0/noctalia.css"
post_hook = "bash /usr/share/noctalia/assets/templates/gtk/apply.sh dark"

[templates.gtk4]
input_path = "/usr/share/noctalia/assets/templates/gtk/noctalia.css"
output_path = "~/.config/gtk-4.0/noctalia.css"
post_hook = "bash /usr/share/noctalia/assets/templates/gtk/apply.sh dark"

[templates.nvim-base16]
input_path = "~/.config/nvim/lua/matugen-template.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = "pkill -SIGUSR1 nvim"

[templates.qt5ct]
input_path = "~/.config/noctalia/templates/noctalia.colors"
output_path = "~/.config/qt5ct/colors/noctalia.conf"

[templates.qt6ct]
input_path = "~/.config/noctalia/templates/noctalia.colors"
output_path = "~/.config/qt6ct/colors/noctalia.conf"

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kitty", "mango", "qt" ]
    community_ids = [ "pywalfox-beta4", "neovim", "fastfetch", "bat", "yazi" ]

[wallpaper]
directory = "/home/leo/dotfiles/resources/wallpapers"

    [wallpaper.automation]
    order = "alphabetical"

    [wallpaper.default]
    path = "/home/leo/dotfiles/resources/wallpapers/wallhaven-3q28qy.jpg"

    [wallpaper.last]
    path = "/home/leo/dotfiles/resources/wallpapers/wallhaven-3q28qy.jpg"

    [wallpaper.monitors.Virtual-1]
    path = "/home/leo/dotfiles/resources/wallpapers/wallhaven-3q28qy.jpg"
